title: Edge Fund 
author: ICTime
email: yubingem@foxmail.com

description: > # this means to ignore newlines until "baseurl:"
  Edge Fund: An CTA Fund exploring market timing with an Edge. Leveraging 10+ years of engineering experties, we are offering non-correlated abnormal returns. 

baseurl: "/mobile'

twitter_username: ICTime 
github_username:  ICTime

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
